<tr>
    <td>%COMPANY_NAME%</td>
    <td>%INDUSTRY_NAME%</td>
    <td>%COMPANY_SIZE%</td>
    <td>%SERVICES_PROVIDED%</td>
    <td>%WEBSITE_OF_COMPANY%</td>
    <td>%ADDED_ON%</td>
    <td>%UPDATED_ON%</td>
</tr>
